name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action step
      id: hello
      uses: erkekin/sort-enums-action@v3
      with:
        who-to-greet: 'ERK DENEME'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
